apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk-pvc
  #namespace: foo
spec:
  storageClassName: "cloud-ssd" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
      
  