apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  #namespace: foo
spec:
  storageClassName: "azurefile" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi